### ISSUE TITLE
Support ordering of migrations 

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [TechnologyBrewery/baton#11]
In the last major feature planned prior to an initial major version release, we'd like to support basic migration ordering and targeting or migrations.  This will not be as complex as something like Flyway, but we'd like to take a cue from them to support the following:

* A type of migration - either "versioned" or "repeatable" (to be provided as part of the `migrations.json` definition)
* Ordered numerically by migration "group and version" tag combination (to be provided as part of the `migrations.json` definition)
* "Minimum version" optional parameter will allow control of older group/versions to ignore
* Each group will be run in its entirety as a unit; groups will not be intermixed
* The plugin will allow groups to be manually ordered.  If no order is specified, then they will be run alphabetically.

This will also be complemented with the ability to inactivate migrations by name.  

For instance, an example of migrations might be something like:
```json
{
    "group": "foo",
    "migrations": [
        {
            "name": "repeatableMigrationExample",
            "type": "repeatable"
        },
        {
            "name": "versionedExampleA",
            "type": "versioned",
            "version": "0.9.0"
        },
        {
            "name": "versionedExampleB",
            "type": "versioned",
            "version": "1.0.0"
        },
        {
            "name": "versionedExampleC",
            "type": "versioned",
            "version": "1.1.0"
        }
    ]
}
```

In the above example, we'd get the following behavior: 
| Minimum Version | repeatableMigrationExample | versionedExampleA | versionedExampleB | versionedExampleC |
|--------|--------|--------|--------|--------|
| | true | true | true | true |
| 0.9.0 | true | true | true | true |
| 1.0.0 | true | false | true | true |
| 1.1.0 | true | false | false | true |
| 1.1.1 | true | false | false | false |

This may prove to be too lightweight and more could be needed - we'll likely continue to iterate from here.

**Comment by jacksondelametter** [comment]
Feature has been merged into Baton.
